language: elixir
elixir:
  - 1.9
  - 1.10
otp_release:
  - 21.0
  - 22.0
script:
  - mix test --trace --cover
  - MIX_ENV=test mix credo --strict
  - mix format --check-formatted
  - cd test/integration
  - mix deps.get
  - mix test --no-start --trace --include integration
services:
  - redis-server
sudo: false
